rethinkdb:
  image: rethinkdb
  ports:
    - '8080:8080'
  volumes:
    - './data:/data'
server:
  build: ./server
  ports:
    - '4567:4567'
  links:
    - rethinkdb
client:
  build: ./client
  links:
    - rethinkdb
  ports:
    - '80:80'
